### ISSUE TITLE
Permission error on temporary file

### ISSUE THREAD

**Issue by amendlik** [warpnet/SublimeLinter-salt-lint#19]
I get these error messages in the Sublime console for every SLS file I open:
```
SublimeLinter: linter.py:1127         salt-lint: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
INFO:SublimeLinter.plugin.salt-lint:salt-lint: Checking lint mode 'background' vs lint reason 'on_load'.  Ok.
SublimeLinter: #37 linter.py:1144     salt-lint: linting 'init.sls'
INFO:SublimeLinter.plugin.salt-lint:salt-lint: linting 'init.sls'
SublimeLinter: #37 linter.py:1699     Running ...

  C:\Users\amendlik\develop\paragon\salt-policy  (working dir)
  > type states\wordpress\init.sls | C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.EXE --nocolour --severity

INFO:SublimeLinter.plugin.salt-lint:Running ...

  C:\Users\amendlik\develop\paragon\salt-policy  (working dir)
  > type states\wordpress\init.sls | C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.EXE --nocolour --severity

SublimeLinter: #37 linter.py:808      WARNING: salt-lint output:
Traceback (most recent call last):
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.EXE\__main__.py", line 7, in <module>
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\saltlint\cli.py", line 72, in run
    os.unlink(stdin_file.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\amendlik\\AppData\\Local\\Temp\\tmplq8m50a9.sls'

WARNING:SublimeLinter.plugin.salt-lint:salt-lint output:
Traceback (most recent call last):
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.EXE\__main__.py", line 7, in <module>
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\saltlint\cli.py", line 72, in run
    os.unlink(stdin_file.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\amendlik\\AppData\\Local\\Temp\\tmplq8m50a9.sls'

SublimeLinter: #37 linter.py:810      Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
INFO:SublimeLinter.plugin.salt-lint:Note: above warning will become an error in the future. Implement `on_stderr` if you think this is wrong.
SublimeLinter: #37 linter.py:1220     salt-lint: no output
INFO:SublimeLinter.plugin.salt-lint:salt-lint: no output
SublimeLinter: sublime_linter.py:593  Linting 'init.sls' took 0.19s
INFO:SublimeLinter.sublime_linter:Linting 'init.sls' took 0.19s
```

**Comment by atezet** [comment]
I have never tested this on Windows and currently no access to a Windows machine. Reading the error it looks like it has to do with the way `salt-lint` lints a file. Have you tried running `salt-lint` on the file directly?

**Comment by amendlik** [comment]
I agree the problem is in salt-lint, and it can be reproduced from the command line. Both products are owned by the same organization in GitHub, so I figured it would get in front of the right people eventually. The problem is triggered specifically by the way that Sublime Text sends the file contents to STDIN, so I opened the issue here.
